### ISSUE TITLE
컴포넌트 만들기

### ISSUE THREAD

**Issue by SE0115** [BC-MOA/MOA-FE#14]
## 이슈 내용
모으기 페이지에 필요한 컴포넌트 만들기

## 상세 내용
이전에 작업한 자유적금 페이지에서 카테고리별 아이콘 부분에서 넘겨주던 en_name props가 코드 수정 후, 불필요해짐. 
하지만 이전 작업 사항 PR 진행 전, 깜빡하고 해당 부분 삭제하지 못해 이번에 해당 부분 코드 삭제함.
## Todo

- [x] 모으기 종류 태그
- [x] 추가 버튼
- [x] 모으기 진행상황
----
- [x] 이전에 작업한 자유적금 페이지에서 카테고리별 아이콘 부분에서 넘겨주던 en_name props 삭제
- [x] 자유 적금 - 이체방법 선택 시, 인풋 초기화
- [x] 모으기 추가 완료 페이지 - 이체방법이 자유인 경우, 수정해주기
