### ISSUE TITLE
모으기 메인 페이지

### ISSUE THREAD

**Issue by SE0115** [BC-MOA/MOA-FE#19]
## 이슈 내용
모으기 메인 페이지 제작

## Todo

- [x] 현재 모은 총 금액 출력
- [x] 모으기 진행중 - 각 종류별 추가 버튼
- [x] 모으기 진행중 - 추가된 모으기 진행상황 보여주기
- [x] 군적금, 목표, 비상금 순서 드래그해서 편집할 수 있도록 기능 추가
- [x] 모으기 완료 - 완료된 모으기 리스트 보여주기 => 아직 디자인이 안나와 임의로 화면 제작.
- [x] **이전 작업**: 모으기 자유적금 페이지 - 계좌선택 select box 수정
