### ISSUE TITLE
군적금 페이지 추가 작업 

### ISSUE THREAD

**Issue by 0andme** [BC-MOA/MOA-FE#23]
## 이슈 내용
군적금 신청 페이지 추가 작업 

## 상세 내용
군적금 신청 페이지에 새롭게 추가된 기능 작업

## Todo
- [x] 약관 이동 아이콘 추가
- [x] 금리이율 / 상품안내 / 유의사항 요소 이미지 추가
- [x] 자동이체 입금 폼 수정 사항 적용
- [x] 군적금 신청 성공시 카드에 표시될 값 전부 수정
- [x] 군적금 신청 시 목표 이름 설정
