### ISSUE TITLE
모으기 상세 페이지

### ISSUE THREAD

**Issue by SE0115** [BC-MOA/MOA-FE#25]
## 이슈 내용
모으기 상세 페이지 작업

## Todo
- [x] 뒤로가기 헤더 - 모으기 이름
- [x] 수정 버튼
- [x] 모으기 디테일 정보 컴포넌트
- [x] 거래내역 컴포넌트
- [x] 수정하기 메뉴 모달창 
- [x] 목표수정 - 군적금
- [x] 목표수정 - 목표
- [x] 자동이체변경 - 군적금
- [x] 자동이체변경 - 목표
- [x] 자동이체등록 - 군적금
- [x] 자동이체등록 - 목표
- [x] 모으기 메인 - 진행중 -> 진행상황 카드에 태그 없애기
- [x] 모으기 메인 - 완료 -> 목표 성공/ 실패 여부 보여주기 
- [x] 비상금 상세 페이지 - 추가 입금 페이지
- [x] 중도해지 페이지
- [x] 중도해지 - 모달창
- [x] 중도해지 - 비밀번호 입력 페이지
- [x] 중도해지 - 완료 페이지
