### ISSUE TITLE
모으기 페이지의 군적금 신청 페이지 작업

### ISSUE THREAD

**Issue by 0andme** [BC-MOA/MOA-FE#5]
## 이슈 내용
모으기 페이지의 군적금 신청 페이지 작업

## Todo
1 페이지 - 적금 안내 페이지
- [x] 군적금 안내 메시지 표시
- [x] 평균  군적금 가입자 표시
- [x] 사용자 적금 리스트 표시
- [x] 적금 상품 클릭시 디테일 페이지로 이동
- [x] 최고금리순/기본금리순 정렬 기능

2 페이지-적금 디테일 페이지
- [x] 클릭된 적금 상품 정보 카드 표시
- [x] 싱품안내/금리안내/안내사항 출력 기능
- [x] 스크롤시 헤더영역에 현재 적금명 표시
- [x] 스크롤시 하단 버튼 생성

3 페이지 - 약관 동의 페이지
- [x] 전체동의 혹은 모든 약관 체크시 다음 버튼 활성화
- [x] 전체동의 상태에서 체크 상태가 하나라도 풀리면 전체동의 상태 해제

4 페이지 - 정보입력 페이지
- [x] 적금방식 선택
- [x] 자동이체시 / 기간 선택 / 월 납입액  선택
- [x] 자동이체시 / 만기예상원금 및 이자 표시
- [x] 자동이체시 / 출금계좌선택
- [x] 자유입금시 / 기간 선택
- [x] 자유입금시 / 출금계좌선택
- [x] 적금방식 변경시 이전 값 초기화
- [x] 모든 폼 입력시 신청완료 버튼 활성화

5 페이지 - 군적금 신청 완료 페이지
- [x] 신청 프로세스 표시
- [x] 신청된 군적금 정보 표시
- [x] 확인버튼 클릭스 모으기 화면으로 이동
