### ISSUE TITLE
챌린지 페이지 추가 작업

### ISSUE THREAD

**Issue by trollering12312** [BC-MOA/MOA-FE#52]
## 이슈 내용

* 챌린지 페이지 디자인이 변경시 작업
* API 설정시 추가 작업
* 기타 추가 작업

## Todo

- [x] 컴포넌트리스트 화면 높이 미세조정
- [x] 베팅 비율별 얻는 열쇠 개수 함수 작성
- [x] 예상 획득 컴포넌트 작성
- [x] 피커에 문구 추가
- [x] 챌린지 상세 연결 - 전체 챌린지 vs 내 챌린지
- [x] 챌린지 상세 선택시 미선택 항목에 grayscale 적용
- [x] 헤더 텍스트 색 조정 - 검은색
