### ISSUE TITLE
챌린지 페이지 탭 컨트롤 컴포넌트 수정

### ISSUE THREAD

**Issue by 0andme** [BC-MOA/MOA-FE#57]
## 이슈 내용
`CompLists.js`의 기존의 컴포넌트를 공통 컴포넌트의 `ContentControlBtn.js` 로 수정
## Todo

- [x] allControlNameList 와 myControlNameList에 한글 컨트롤 목록을 선언
- [x] ContentControlBtn 컴포넌트의 프롭스 setListControl 를 통해 filter와 Done값을 클릭된 컨트롤 값으로 변경
- [x] AllList 컴포넌트나 MyList 컴포넌트의 cond값에 한글이 아닌 영문으로 작성된 값을 넣어주기 위해 프롭스 cond에 setFilterWrapper/setDoneWrapper함수의 리턴값을 넣어줌 
- [x] setFilterWrapper/setDoneWrapper함수는 현재 filter/Done 값을 확인하여 영문/불린 값을 리턴

**Comment by trollering12312** [comment]
확인했습니다!
