### ISSUE TITLE
자유적금 페이지 제작

### ISSUE THREAD

**Issue by SE0115** [BC-MOA/MOA-FE#6]
## 이슈 내용
모으기 페이지 내 자유적금 페이지 제작

## Todo
- [x] 뒤로가기 버튼
- [x] 목표 카테고리 설정
- [x] 목표 이름 / 만기일 설정
- [x] 입금 방식 - 자동이체
- [x] 입금 방식 - 자유입금
- [x] 예상 원금 표시
- [x] 출금 계좌 선택
- [x] 목표 설정 완료 페이지
- [x] check 애니메이션 추가
- [x] 아이콘 svg 색 변경 가능하도록 수정
