### ISSUE TITLE
로그인 이후 홈 페이지 및 군적금 개수에 따른 각 컴포넌트작업

### ISSUE THREAD

**Issue by 0andme** [BC-MOA/MOA-FE#62]
## Todo

군적금 계좌 및 적금 연동 전 컴포넌트
- [x] 추후 작업

군적금 계좌 연동 후 컴포넌트
- [x] 금액 표시 컴포넌트
- [x] 군적금 개수에 따른 말풍선 컴포넌트

아래 내용 추후 작업
- [x] 0개일때 가입가능한 적금 리스트 보여주기
- [x] 1개일 때 가입 중인 군적금 컴포넌트 보여주기
- [x] 1개일때 버튼 클릭시 군적금 추가 라우터로 이동
- [x] 2개일 때 버튼 클릭시 모으기 라우터로 이동

군적금 여부와 상관없는 컴포넌트
- [x] 상단 헤더
- [x] 하단 네비게이션 바
- [x] 진행 챌린지 표시
- [x] 리워드 박스 안내 이미지
